#version 130
#define Calc_Sky_With_Fog
#define Calc_Lighting_Color_With_Fog
#define Calc_Natural_Light_Color
#define Gen_Water_Color
#define Gen_TnR
#define Void_Sky
#define RefctionsDirection
#include "../program/composite.vsh"
